### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by hellof3** [hellof3/SEBC#7]

**Comment by hellof3** [comment]
terriable network!

**Comment by hellof3** [comment]
i download the CDH parcel and CM package on my local labtop and upload to the AWS,the time is gone!

**Comment by mfernest** [comment]
There were a couple students who had this experience. I am sorry it prevented you from submitting more work.

You may retake the challenge if you would like. If you are interested I will send out details.

**Comment by hellof3** [comment]
yes,please tell me the details,thank you!
